### ISSUE TITLE
Send/receive control commands over TLS

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdbd-vpn#11]

**Comment by claytondus** [comment]
Proposed format:
-Magic number (16 bits) - 0xCDBD
-Message type (8 bits)
-Message length in 32-bit words (8 bits) 
-SPI
-Data

Message types:
-00: Session Key
-01: IV
-02: Break
-03: Route Information
-04: SPI Information (will start the tunnel)

**Comment by BrandonDenton** [comment]
working on that now, will update my branch once I have it functioning

**Comment by claytondus** [comment]
Are you implementing this on top of tls_server.c, or are you working separately?  We have to change the server slightly so it will accept connections continuously.  I'm planning on the client opening the TLS connection, sending its commands, receiving commands from the server (if any, perhaps the tunnel ID to refer to later), and closing the connection.  Subsequent commands will open a new connection.  I suggest this because multithreading OpenSSL 1.0x is a hassle, as you probably have learned, and I don't see any reason for keeping the TLS connection open.  This is similar to SIP works over TCP; it sets up a telephone call over RTP on UDP, and then closes TCP down.

**Comment by BrandonDenton** [comment]
I was building off tls_server.c. And you're right; I'd rather not keep a connection open continuously anyway. I'll keep that in mind.

**Comment by claytondus** [comment]
I wound up writing this fast since I did the client side, I'm debugging it now.

**Comment by claytondus** [comment]
All commands working as expected.
