### ISSUE TITLE
Set up tunnels from config info

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdbd-vpn#3]

**Comment by claytondus** [comment]
defs variable contains tunnel definitions (remote IP, port, key, etc.).  tun_sock is the local socket used for sending/receiving from the tun interface.  The TLS process needs to insert its information into defs[n] to configure the UDP tunnel.

**Comment by BrandonDenton** [comment]
passing config info in cdbd-vpn.c to the defs struct
